// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgeneration.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import documentgeneration.implementation.DocumentRequestManager;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_ExecutePageMicroflow extends UserAction<java.lang.Void>
{
	/** @deprecated use documentRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __documentRequest;
	private final documentgeneration.proxies.DocumentRequest documentRequest;

	public JA_ExecutePageMicroflow(
		IContext context,
		IMendixObject _documentRequest
	)
	{
		super(context);
		this.__documentRequest = _documentRequest;
		this.documentRequest = _documentRequest == null ? null : documentgeneration.proxies.DocumentRequest.initialize(getContext(), _documentRequest);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		DocumentRequestManager.executePageMicroflow(documentRequest, getContext());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ExecutePageMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
