// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgeneration.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import documentgeneration.implementation.ConfigurationManager;
import documentgeneration.proxies.Enum_ServiceType;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_GetServiceType extends UserAction<java.lang.String>
{
	public JA_GetServiceType(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		switch (ConfigurationManager.getServiceType()) {
			case LOCAL:
				return Enum_ServiceType._Local.toString();

			case CLOUD:
				return Enum_ServiceType._Cloud.toString();

			case PRIVATE:
				return Enum_ServiceType._Private.toString();

			default:
				throw new RuntimeException("Invalid service type");
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetServiceType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
