// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgeneration.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import documentgeneration.implementation.ConfigurationManager;
import documentgeneration.proxies.Configuration;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_Registration_Manual extends UserAction<java.lang.Boolean>
{
	/** @deprecated use registrationWizard.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __registrationWizard;
	private final documentgeneration.proxies.RegistrationWizard registrationWizard;

	public JA_Registration_Manual(
		IContext context,
		IMendixObject _registrationWizard
	)
	{
		super(context);
		this.__registrationWizard = _registrationWizard;
		this.registrationWizard = _registrationWizard == null ? null : documentgeneration.proxies.RegistrationWizard.initialize(getContext(), _registrationWizard);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Configuration configuration = ConfigurationManager.getConfigurationObject(getContext());
		configuration.setApplicationUrl(registrationWizard.getApplicationUrl());

		ConfigurationManager.updateTokenInformation(configuration,
				registrationWizard.getManualAccessToken(),
				registrationWizard.getManualRefreshToken(), 0);

		configuration.commit(getContext());

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Registration_Manual";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
